site_name: "Generator Spring Boot"
site_description: "The Yeoman generator for generating Spring Boot microservices"
site_author: "chensoul"
site_url: "https://chensoul.github.io/generator-springboot"

# Repository
repo_name: "chensoul/generator-springboot"
repo_url: "https://github.com/chensoul/generator-springboot"

# Copyright
copyright: "Copyright &copy; 2024 Chensoul"

theme:
  name: material
nav:
  - Home: index.md

# Customization
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/chensoul"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/ichensoul"

# Extensions
markdown_extensions:
  - codehilite
  - tables
