services:
  <%= appName %>:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - <%= databaseType %>
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      <%_ if (databaseType === 'postgresql') { _%>
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://<%= databaseType %>:5432/appdb
      <%_ } _%>
      <%_ if (databaseType === 'mysql') { _%>
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mysql://<%= databaseType %>:3306/appdb
      <%_ } _%>
      <%_ if (databaseType === 'mariadb') { _%>
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mariadb://<%= databaseType %>:3306/appdb
      <%_ } _%>
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=secret
      <%_ if (loggingType === 'loki' ) { _%>
      - APPLICATION_LOKI_URL=http://loki:3100/loki/api/v1/push
      <%_ } _%>
      <%_ if (features.includes('zipkin')) { _%>
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
      <%_ } _%>
      <%_ if (features.includes('tempo')) { _%>
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411/api/v2/spans
      <%_ } _%>