server.port: 8080

server:
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024

spring.application.name: <%=appName %>
spring.main.allow-bean-definition-overriding: true
spring.jmx.enabled: false
spring.mvc.problemdetails.enabled: true

################ Database #####################
spring.datasource.hikari.auto-commit: false
spring.datasource.hikari.data-source-properties.ApplicationName: ${spring.application.name}
  <%_ if (databaseType === 'postgresql') { _%>
spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://localhost:5432/appdb
  <%_ } _%>
  <%_ if (databaseType === 'mysql') { _%>
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/appdb
  <%_ } _%>
  <%_ if (databaseType === 'mariadb') { _%>
spring.datasource.driver-class-name: org.mariadb.jdbc.Driver
spring.datasource.url: jdbc:mariadb://localhost:3306/appdb
  <%_ } _%>
spring.datasource.username: appuser
spring.datasource.password: secret
  
  <%_ if (persistence === 'jpa') { _%>
spring.data.jpa.repositories.bootstrap-mode: deferred
spring.jpa.show-sql: false
spring.jpa.open-in-view: false
spring.jpa.hibernate.ddl-auto: none
#spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.jdbc.time_zone: UTC
spring.jpa.properties.hibernate.generate_statistics: false
spring.jpa.properties.hibernate.jdbc.batch_size: 25
spring.jpa.properties.hibernate.order_inserts: true
spring.jpa.properties.hibernate.order_updates: true
spring.jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch: true
spring.jpa.properties.hibernate.query.in_clause_parameter_padding: true
spring.jpa.properties.hibernate.query.plan_cache_max_size: 4096
spring.jpa.properties.hibernate.connection.provider_disables_autocommit: true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
  <%_ } _%>
  <%_ if (persistence === 'mybatis') { _%>
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  <%_ } _%>

  <%_ if (dbMigrationTool === 'flywaydb') { _%>
spring.flyway.locations: classpath:/db/migration/{vendor}
  <%_ } _%>

  <%_ if (features.includes('localstack')) { _%>
###AWS
spring.cloud.aws.endpoint: http://localhost:4566
spring.cloud.aws.credentials.access-key: noop
spring.cloud.aws.credentials.secret-key: noop
spring.cloud.aws.region.static: us-east-1
  <%_ } _%>

################ Actuator #####################
management.endpoints.web.exposure.include: configprops,env,health,info,logfile,loggers,metrics,prometheus,aggmetrics
management.endpoint.health.show-details: always
  <%_ if (features.includes('zipkin') || features.includes('monitor') ) { _%>
management.tracing.sampling.probability: 1.0
management.zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans
  <%_ } _%>
  
  <%_ if (loggingType === 'loki') { _%>
application.loki.url: http://localhost:3100/loki/api/v1/push
  <%_ } _%>