const LOCALSTACK_IMAGE_VERSION = '3.3.0';
const POSTGRESQL_IMAGE_VERSION = '17';
const MARIADB_IMAGE_VERSION = '11.4';
const MYSQL_IMAGE_VERSION = '8.4.0';

module.exports = {
    JAVA_VERSION: '17',
    DEFAULT_APP_VERSION: '0.0.1-SNAPSHOT',
    SPRING_BOOT_VERSION: '3.3.5',
    SPRING_CLOUD_VERSION: '2023.0.3',
    SPRING_CLOUD_AWS_VERSION: '3.1.1',
    SPRING_DEP_MNGMNT_VERSION: '1.1.6',
    MYBATIS_PLUS_VERSION: '3.5.8',
    SPRINGDOC_OPENAPI_VERSION: '2.6.0',
    COMMONS_IO_VERSION: '2.16.1',
    LOKI_LOGBACK_APPENDER: '1.3.2',
    PALANTIR_JAVA_FORMAT_VERSION: '2.50.0',

    JACOCO_MIN_COVERAGE_REQUIRED: '0.80',

    GRADLE_GIT_PROPERTIES_PLUGIN_VERSION: '2.4.2',
    GRADLE_JACOCO_PLUGIN_VERSION: '0.8.12',
    GRADLE_SONAR_PLUGIN_VERSION: '5.1.0.4882',
    GRADLE_BENMANES_VERSIONS_PLUGIN_VERSION: '0.51.0',
    GRADLE_SPOTLESS_PLUGIN_VERSION: '6.25.0',

    MAVEN_DEPENDENCY_CHECK_PLUGIN_VERSION: '10.0.3',
    MAVEN_PROPERTIES_PLUGIN_VERSION: '1.2.1',
    MAVEN_SONAR_PLUGIN_VERSION: '4.0.0.4121',
    MAVEN_JACOCO_PLUGIN_VERSION: '0.8.12',
    MAVEN_SPOTLESS_PLUGIN_VERSION: '2.43.0',

    KEY_FLYWAY_MIGRATION_COUNTER: 'flywayMigrationCounter',
    KEY_LIQUIBASE_MIGRATION_COUNTER: 'liquibaseMigrationCounter',

    LOCALSTACK_IMAGE_VERSION: LOCALSTACK_IMAGE_VERSION,
    LOCALSTACK_IMAGE: 'localstack/localstack:' + LOCALSTACK_IMAGE_VERSION,

    POSTGRESQL_IMAGE_VERSION: POSTGRESQL_IMAGE_VERSION,
    POSTGRESQL_IMAGE: 'postgres:' + POSTGRESQL_IMAGE_VERSION,

    MARIADB_IMAGE_VERSION: MARIADB_IMAGE_VERSION,
    MARIADB_IMAGE: 'mariadb:' + MARIADB_IMAGE_VERSION,

    MYSQL_IMAGE_VERSION: MYSQL_IMAGE_VERSION,
    MYSQL_IMAGE: 'mysql:' + MYSQL_IMAGE_VERSION,

    JDK_IMAGE_VERSION: '17.0.12_7-jre-jammy',
    ES_IMAGE_VERSION: '8.15.3',
    GRAFANA_IMAGE_VERSION: '11.2.2',
    SONARQUBE_IMAGE_VERSION: '9.9.7-community',
    PROMETHEUS_IMAGE_VERSION: 'v2.54.1',
}
