server.port: 8080

server:
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024

spring.application.name: myservice
spring.main.allow-bean-definition-overriding: true
spring.jmx.enabled: false
spring:
  mvc:
    problemdetails:
      enabled: true

################ Database #####################
spring.datasource.hikari.auto-commit: false
spring.datasource.hikari.connection-timeout: 30000
spring.datasource.hikari.maximum-pool-size: 10
spring.datasource.hikari.data-source-properties.ApplicationName: ${spring.application.name}
spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://localhost:5432/appdb
spring.datasource.username: appuser
spring.datasource.password: secret

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring.flyway.locations: classpath:/db/migration/{vendor}

################ Actuator #####################
management.endpoints.web.exposure.include: configprops,env,health,info,logfile,loggers,metrics,prometheus
management.endpoint.health.show-details: always
management.tracing.sampling.probability: 1.0
management.zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans


error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
