services:
  sonar:
    image: sonarqube:9.9.7-community
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    ports:
      - "9001:9000"
      - "9000:9000"

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"

